# Generated by Django 5.1.2 on 2024-10-31 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_journey_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='status',
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(1, 'Статус 1'), (2, 'Статус 2'), (10, 'Статус 10')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='street',
            name='workload',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
